language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0

    - php: 7.2
      env: STATIC_ANALYSIS=1 DEFAULT=0

before_script:
  - phpenv config-rm xdebug.ini

  - sudo apt-get install wkhtmltopdf -y
  - sudo touch /usr/bin/latexpdf && sudo chmod +x /usr/bin/latexpdf

  - composer update --no-interaction

  - if [[ $PHPCS = 1 ]]; then composer require --dev cakephp/cakephp-codesniffer:^4.0; fi

  - if [[ $STATIC_ANALYSIS = 1 ]]; then composer require --dev phpstan/phpstan:^0.12 psalm/phar:^3.7; fi

script:
  - |
      if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.2 ]]; then
        mkdir -p build/logs
        vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
      fi
  - if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION != 7.2 ]]; then vendor/bin/phpunit; fi

  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests/TestCase ./config; fi

  - if [[ $STATIC_ANALYSIS = 1 ]]; then vendor/bin/phpstan.phar analyze src/ && vendor/bin/psalm.phar; fi

after_success:
  - |
      if [[ $DEFAULT = 1 && $TRAVIS_PHP_VERSION = 7.2 ]]; then
        wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
        chmod +x php-coveralls.phar
        ./php-coveralls.phar
      fi

notifications:
  email: false
